services:
  app:
    build:
      args:
        user: davin
        uid: 1000
      context: ./
      dockerfile : Dockerfile
    image: davingreg/laraveldavin  
    container_name: laraveldavin-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./:/var/www
    networks:
      - projets
  # db: 
  #   image: mysql:8.2.0
  #   container_name: laraveldavin-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE : ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
  #     MYSQL_PASSWORD : ${DB_PASSOWRD}
  #     MYSQL_USERNAME: ${DB_USERNAME}
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #     SERVICE_NAME: mysql
  #   ports:
  #     - 4306:3306
  #   volumes:
  #      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #      - projets 

  nginx:
    image: nginx:1.25.3-alpine
    restart: unless-stopped
    container_name: laraveldavin-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - projets

networks:
  projets : 
    driver : bridge
