apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: laraveldavin-app-deployment
spec:
  selector:
    matchLabels:
      app: laraveldavin-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: laraveldavin-app
    spec:
      containers:
        - name: laraveldavin-app
          image: davingreg/laraveldavin # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: laraveldavin-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31110